### ISSUE TITLE
Export `cmd` as `standard`.

### ISSUE THREAD

**Issue by chenxsan** [feross/standard-react#4]
The `cmd` exported is `standard-react`. If I want to use standard-react in VS Code, then I need to modify my extension code here https://github.com/chenxsan/vscode-standardjs/blob/master/eslint-server/src/server.ts#L103, or maybe publish another extension.

Since standard-react is kinda an enhancement version of standard, I'm wondering if it's all right to publish it as `standard` in cmd.

**Comment by feross** [comment]
Sorry, I would prefer to keep the `standard` command consistent so it always runs the mainstream version of standard.
